version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 300
      runas: ec2-user