export const LOGIN = 'LOGIN';
export const CHECK_IS_LOGIN = 'CHECK_IS_LOGIN';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const REQ_RESET_PASSWORD = 'REQ_RESET_PASSWORD';
export const SIGNUP = 'SIGNUP';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const CONTACT_US = 'CONTACT_US';

// Blog Constants
export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOG = 'GET_BLOG';

// Appoitment Constants
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CREATE_APPOINTMENT_ERROR = 'CREATE_APPOINTMENT_ERROR';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';

// GetUser By Access ID
export const GET_USER_BY_ACCESS_ID = 'GET_USER_BY_ACCESS_ID';

export const GET_BOOKING_STATUS = 'GET_BOOKING_STATUS';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_APPOINTMENT_LIST = 'GET_APPOINTMENT_LIST';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_TOPIC = 'GET_TOPIC';

export const SEARCH_LECTURE = 'SEARCH_LECTURE';

export const SEARCH_KIRTAN = 'SEARCH_KIRTAN';

export const GET_MKV = 'GET_MKV';

export const UPDATE_COUNTERS = 'UPDATE_COUNTERS';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_REPLIES = 'GET_REPLIES';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_REPLIES = 'CREATE_REPLIES';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_REPLY = 'DELETE_REPLY';

export const GET_GALLERY = 'GET_GALLERY';
export const GET_STATIC_GALLERY = 'GET_STATIC_GALLERY';
export const GET_SUB_GALLERY = 'GET_SUB_GALLERY';
